[package]
name = "graas"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-rs = "0.20.7"
glib = "0.20.9"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_14"] }
sourceview5 = "0.9.1"
