name: Rust Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          rustup update
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test
